server.port: 7002

spring.application.name: demo2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1

logging.level.com.example: DEBUG
