server.port: 7001

spring.application.name: demo1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1

logging.level.com.example: DEBUG
